<?php

App::singleton('AccessControl', function()  { 
			return  new AccessControl(Auth::user()->id, Auth::user()->role_id);
}); 


if (Auth::check() ) {	
	$acessControl = App::make('AccessControl');
	View::share('accessControl', $acessControl);
	View::share('uri', Input::segment(1));
	View::share('page_limit', 10);
}


// dd($acessControl->getRoleName(24));


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


// =============== Experimental ===================

Route::get('/', ['as' => 'main',function()
{

ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);
date_default_timezone_set('Europe/London');

if (PHP_SAPI == 'cli')
	die('This example should only be run from a Web Browser');

/** Include PHPExcel */
// require_once dirname(__FILE__) . '/../Classes/PHPExcel.php';


// Create new PHPExcel object
$objPHPExcel = new PHPExcel();

// Set document properties
$objPHPExcel->getProperties()->setCreator("James Norman Mones Jr.")
							 ->setLastModifiedBy("James Norman Mones Jr.")
							 ->setTitle("CONSOLIDATED PAYROLL for JUNE 01 TO 14, 2014")
							 ->setSubject("Office 2007 XLSX Test Document")
							 ->setDescription("CONSOLIDATED PAYROLL for JUNE 01 TO 14, 2014 generated by HR and Payroll System.")
							 ->setKeywords("office 2007 openxml php payroll")
							 ->setCategory("Payroll");


// Add some data
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue('A1', "ID Number");
$objPHPExcel->getActiveSheet()->setCellValue('B1', "Name");
$objPHPExcel->getActiveSheet()->setCellValue('C1', "Ndays");
$objPHPExcel->getActiveSheet()->setCellValue('D1', "Basic");
$objPHPExcel->getActiveSheet()->setCellValue('E1', "Incentive");
$objPHPExcel->getActiveSheet()->setCellValue('F1', "Overtime");
$objPHPExcel->getActiveSheet()->setCellValue('G1', "NPremium");
$objPHPExcel->getActiveSheet()->setCellValue('H1', "Adjustment");
$objPHPExcel->getActiveSheet()->setCellValue('I1', "Gross");
$objPHPExcel->getActiveSheet()->setCellValue('J1', "HDMF");
$objPHPExcel->getActiveSheet()->setCellValue('K1', "SSS");
$objPHPExcel->getActiveSheet()->setCellValue('L1', "PHIC");
$objPHPExcel->getActiveSheet()->setCellValue('M1', "SSS Loan");
$objPHPExcel->getActiveSheet()->setCellValue('N1', "HDMF Loan");
$objPHPExcel->getActiveSheet()->setCellValue('O1', "Health Care");
$objPHPExcel->getActiveSheet()->setCellValue('P1', "CBU");
$objPHPExcel->getActiveSheet()->setCellValue('Q1', "Pledge");
$objPHPExcel->getActiveSheet()->setCellValue('R1', "Pharmacy");
$objPHPExcel->getActiveSheet()->setCellValue('S1', "Overtime");
$objPHPExcel->getActiveSheet()->setCellValue('T1', "Ticket");
$objPHPExcel->getActiveSheet()->setCellValue('U1', "Grocery");
$objPHPExcel->getActiveSheet()->setCellValue('V1', "Savings");
$objPHPExcel->getActiveSheet()->setCellValue('W1', "Adjustment");
$objPHPExcel->getActiveSheet()->setCellValue('X1', "Netpay");






// Rename worksheet
$objPHPExcel->getActiveSheet()->setTitle('Simple');
$objPHPExcel->getActiveSheet()->freezePane('A2');


for ($i = 2; $i <= 5000; $i++) {
	$objPHPExcel->getActiveSheet()->setCellValue('A' . $i, "FName $i")
	                              ->setCellValue('B' . $i, "LName $i")
	                              ->setCellValue('C' . $i, "PhoneNo $i")
	                              ->setCellValue('D' . $i, "FaxNo $i")
	                              ->setCellValue('E' . $i, true);
}


$objPHPExcel->getActiveSheet()->getStyle('A1:T100')->applyFromArray(
	array(
		  'borders' => array(
								'bottom'	=> array('style' => PHPExcel_Style_Border::BORDER_THIN),
								'right'		=> array('style' => PHPExcel_Style_Border::BORDER_MEDIUM)
							)
		 )
	);

// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);


// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="01simple.xlsx"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');

}]);





Route::get('/demo', function()
{
	// $objPHPExcel = new PHPExcel();
	// $filename = "C:\Tibud\sssloan december.xls";
	// $objPHPExcel = PHPExcel_IOFactory::load("C:\Tibud\New data\chunk.xlsx");
	// // $excelReader = PHPExcel_IOFactory::createReaderForFile($filename);



	$jExcel = App::make('Acme\Extension\jExcel');

	$jExcel->loadFile("C:\Tibud\New data\chunk.xlsx");


	$jExcel->getFieldAndValues();



	$employees = App::make('Acme\Repositories\Employee\EmployeeRepositoryInterface');

	Event::listen('illuminate.query', function ($sql, $bindings, $times) {
			echo '<h3 class="page-header">Database Query</h3>';
				var_dump($sql);
		});

	// dd( $jExcel->convertValuesAndFieldsToDBArray(true) );

		try {
			$data = $jExcel->convertValuesAndFieldsToDBArray(true);

			// DB::table('employees')->insert($data);
		} catch (Exception $e) {
			echo $e->getMessage();
		}	

	return '';
});




// ============= Authentication ==================
Route::get('login', 'AuthController@index' );
Route::post('login/auth', 'AuthController@login' );
Route::get('logout', 'AuthController@logout' ); 



// ============ File Maintenance =================
Route::group(array('before' => 'auth'), function()
{

   // ========= GETTING SYNCHRONOUS DATA ==========
	Route::get('syncdata', 'SyncController@index');

   // Philhealth Controller
	Route::resource('hdmf', 'HDMFController');

	// Departments Controller
	Route::get('departments/departmentsByCompany', 'DepartmentsController@departmentsByCompany');
	Route::resource('departments', 'DepartmentsController');

	// Position Controller
	Route::get('positions/positionsByDepartment', 'PositionsController@positionsByDepartment');
	Route::resource('positions', 'PositionsController');


	Route::resource('sss', 'SSSController');
	Route::resource('philhealth', 'PhilhealthsController');


	// User controller
   Route::resource('users', 'UsersController');
   
	Route::resource('philhealths', 'PhilhealthsController');

	Route::resource('companies', 'CompaniesController');

	Route::resource('work_assignments', 'WorkAssignmentsController');

	Route::resource('requirements', 'RequirementsController');

	Route::resource('stageprocesses', 'StageProcessesController');
	
});

// =========== HR Module ================
Route::group(array('before' => ['auth']), function()
{
	// ==================== Violation ================================
	Route::resource('offenses', 'ViolationsOffensesController');	
	Route::resource('violations', 'ViolationsController');	

	// ==================== Disciplinary Actions =====================
	Route::resource('employees/disciplinary_actions', 'DisciplinaryActionsController');	

	// ==================== Medical Establishments  ==================
	Route::resource('employees/medical_examinations/establishments', 'MedicalEstablishmentsController');	
		
	// ==================== Medical Establishments  ==================
	Route::resource('employees/medical_examinations/diseases', 'DiseasesController');	
	

	// ============== Annual Medical Examination Module ==============
	Route::resource('employees/medical_examinations', 'EmployeesMedicalExaminationsController');

	// Employee Controller
    Route::resource('employees', 'EmployeesController');
	Route::get('employees/promote', 'EmployeesController@promoteview');
	Route::get('employees/getposition', 'EmployeesController@getPosition');
	Route::post('promote', 'EmployeesController@promote');
	Route::post('employees/photo', 'EmployeesPhotoController@upload');


	// Applicants
	Route::post('applicants/requirements', 'ApplicantsController@requirements');
	Route::get('applicants/jsonApplicantInfo', 'ApplicantsController@jsonApplicantInfo');
	Route::patch('applicants/jsonApplicant', 'ApplicantsController@jsonUpdateApplicant');
	Route::resource('applicants', 'ApplicantsController');



   	Route::post('leaves/approve', 'LeavesController@approve');
	Route::post('leaves/reject', 'LeavesController@reject');
	Route::resource('leaves', 'LeavesController');


	Route::resource('sss_loans', 'SSS_loansController');
	Route::resource('holidays', 'HolidaysController');


	// ============== Timekeeping Module ==============
	// Route::resource('timekeeping', 'TimekeepingsController'); Not yet required
});



// ============= Payroll Module =============
Route::group(array('before' => 'auth', 'prefix' => 'payroll'), function()
{
	Route::resource('dtr', 'DTRController');

	Route::get('rates/forSelect', 'RatesController@forSelect');
	Route::resource('rates', 'RatesController');
	Route::resource('pay_period', 'PayPeriodsController');
	Route::post('process', 'PayrollController@process');
	Route::get('export', 'PayrollController@export');
	
});

// =========== Settings =====================
Route::group(array('before' => 'auth'), function()
{
	Route::resource('payroll', 'PayrollController');
	Route::get('settings', 'SettingsController@index' );
	Route::resource('settings/roles', 'RolesController');
});

// =========== AUX =====================
Route::group(array('before' => 'auth'), function()
{
	Route::get('/import', 'ImportsController@create');
	Route::post('/import/upload', 'ImportsController@upload');
	Route::post('/import/start', 'ImportsController@start');
});



// =============================================
// CATCH ALL ROUTE =============================
// =============================================
// all routes that are not home or api will be redirected to the frontend
// this allows angular to route them
App::missing(function($exception)
{
	return Response::view('layout.missing_page', array(), 404);
});







